Trying to resolve a problem with an an unknown logger being called when an agent timeout occurs.
Exception was:
/Users/glenn/src/git/nanite/lib/nanite/mapper.rb:283:in `check_timeouts': undefined method `log' for Nanite:Module (NoMethodError)